@startuml
artifact "bcrypt_hasher/src/lib.rs"
artifact "entities/src/category.rs"
artifact "entities/src/date_serde.rs"
artifact "entities/src/datetime_serde.rs"
artifact "entities/src/lib.rs"
artifact "entities/src/request.rs"
artifact "entities/src/tournament.rs"
artifact "entities/src/training.rs"
artifact "entities/src/tuition.rs"
artifact "entities/src/user.rs"
artifact "http_api/src/auth.rs"
artifact "http_api/src/category_endpoints.rs"
artifact "http_api/src/err.rs"
artifact "http_api/src/main.rs"
artifact "http_api/src/request_endpoints.rs"
artifact "http_api/src/tournament_endpoints.rs"
artifact "http_api/src/training_endpoints.rs"
artifact "http_api/src/tuition_endpoints.rs"
artifact "http_api/src/user_endpoints.rs"
artifact "turso_db/src/category_repo/mod.rs"
artifact "use_cases/src/category_service/err.rs"
artifact "use_cases/src/category_service/mod.rs"
artifact "use_cases/src/category_service/repository_trait.rs"
artifact "use_cases/src/lib.rs"
artifact "use_cases/src/request_service/err.rs"
artifact "use_cases/src/request_service/mod.rs"
artifact "use_cases/src/request_service/repository_trait.rs"
artifact "use_cases/src/tournament_service/err.rs"
artifact "use_cases/src/tournament_service/mod.rs"
artifact "use_cases/src/tournament_service/repository_trait.rs"
artifact "use_cases/src/training_service/err.rs"
artifact "use_cases/src/training_service/mod.rs"
artifact "use_cases/src/training_service/repository_trait.rs"
artifact "use_cases/src/tuition_service/err.rs"
artifact "use_cases/src/tuition_service/mod.rs"
artifact "use_cases/src/tuition_service/repository_trait.rs"
artifact "use_cases/src/tuition_service/tests.rs"
artifact "use_cases/src/user_service/err.rs"
artifact "use_cases/src/user_service/hasher_trait.rs"
artifact "use_cases/src/user_service/mod.rs"
artifact "use_cases/src/user_service/repository_trait.rs"
artifact "use_cases/src/user_service/unique_identifier.rs"
artifact ".env"
@enduml