@startuml
title Actor: Entrenador
start
:Seleccionar "Enviar solicitud de registro de usuario";
:Ingresar datos de registro;
:Enviar solicitud;
if (¿Datos válidos?) then (Sí)
  :Enviar solicitud al administrador;
  :Mostrar confirmación;
else (No)
  :Mostrar error;
endif
stop
@enduml