@startuml
title Actor: Admin
start
:Seleccionar "Actualizar información de usuarios";
:Buscar usuario;
:Seleccionar usuario;
:Editar detalles del usuario;
:Guardar cambios;
if (¿Datos válidos?) then (Sí)
  :Actualizar registro del usuario;
  :Mostrar éxito;
else (No)
  :Mostrar error;
endif
stop
@enduml